# Configuration
# Use UNC paths when running over the network from another machine
input_file: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\export_everwin (19).xlsx'
input_file_cleaned_1: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase1_output\export_phase1_cleaned.csv'
input_file_cleaned_3_all: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase3_output\phase3_cleaned_all.csv'
input_file_cleaned_3_multi: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase3_output\phase3_cleaned_multivariate.csv'
input_file_cleaned_3_univ: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase3_output\phase3_cleaned_univ.csv'

output_dir: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase4_output'
metrics_dir: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\METRICS_DIR'
data_dictionary: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase1_output\data_dictionary_complet.xlsx'
output_pdf: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase4_output\phase4_report.pdf'

n_jobs: -1
optimize_params: false
methods: [famd, pca, mca, mfa, umap, pacmap, phate]

# Method specific options (can be left empty)
famd:
  n_components: 12
  # Let fine-tuning choose the component rule (variance, kaiser or elbow)
  n_components_rule:
  variance_threshold: 0.9
mfa:
  n_components: 10
  weights: null
  segment_col: "Statut commercial"
  # Specify groups only if you want to restrict variables.
  # By default (groups: null), all variables are included automatically.
  groups: null
pca: {n_components: 3, svd_solver: randomized, whiten: true}
mca: {n_components: 15, normalize: false, n_iter: 5}
umap:
  n_neighbors: 30
  min_dist: 0.1
  n_jobs: -1
  # metric will be selected during fine-tuning
  metric: cosine
  n_components: 2
phate:
  n_components: 3
  knn: 15
  t: 20
  decay: 20
  # n_components selected by fine tuning
pacmap:
  n_components: 3
  n_neighbors: 5
  MN_ratio: 0.5
