# Example configuration for phase4v2.py
# Adjust the paths as needed. Below reflects the original dataset location used
# when `phase4_famd.py` was created.
# Use UNC paths when running over the network from another machine
input_file: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\export_everwin (19).xlsx'
output_dir: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase4_output'
metrics_dir: '\\Lenovo\d\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\METRICS_DIR'
n_jobs: -1
optimize_params: false
methods: [famd, pca, mca, mfa, pcamix, umap, pacmap, phate, tsne]

# Method specific options (can be left empty)
famd:
  weighting: balanced
  # Let fine-tuning choose the component rule (variance, kaiser or elbow)
  n_components_rule:
  variance_threshold: 0.9
mfa:
  segment_col: "Statut commercial"
  # Specify groups only if you want to restrict variables.
  # By default (groups: null), all variables are included automatically.
  groups: null
pca: {}
mca: {}
pcamix: {}
umap:
  n_jobs: -1
  # metric will be selected during fine-tuning
  metric:
tsne: {}
phate:
  knn: auto
  t: auto
  # n_components selected by fine tuning
