# Example configuration for phase4v2.py
# Adjust the paths as needed. Below reflects the original dataset location used
# when `phase4_famd.py` was created.
input_file: 'D:\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\export_everwin (19).xlsx'
output_dir: 'D:\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase4_output'
metrics_dir: 'D:\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\METRICS_DIR'
n_jobs: 2
stop_after_prep: false
optimize_params: false
methods: [famd, pca, mca, mfa, pcamix, umap, pacmap, phate, tsne]

# Method specific options (can be left empty)
famd:
  weighting: balanced
  n_components_rule: variance  # 'variance', 'kaiser' or 'elbow'
  variance_threshold: 0.9
mfa:
  segment_col: "Statut commercial"
  # Specify groups only if you want to restrict variables.
  # By default (groups: null), all variables are included automatically.
  groups: null
pca: {}
mca: {}
pcamix: {}
umap:
  # Use all CPU cores by default. Set `random_state` if you need
  # reproducibility; UMAP will then run single-threaded.
  random_state: null
  n_jobs: -1
  metric: euclidean
tsne: {}
phate:
  knn: 5       # nombre de voisins ("auto" pour laisser PHATE décider)
  t: auto      # étapes de diffusion
  n_components: 2
