# Example configuration for phase4v2.py
# Adjust the paths as needed. Below reflects the original dataset location used
# when `phase4_famd.py` was created.
input_file: 'D:\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\export_everwin (19).xlsx'
output_dir: 'D:\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\phase4_output'
metrics_dir: 'D:\DATAPREDICT\DATAPREDICT 2024\Missions\Digora\METRICS_DIR'
optimize_params: false
methods: [famd, pca, mca, mfa, pcamix, umap, pacmap, phate, tsne]

# Method specific options (can be left empty)
famd: {}
mfa: {}
pca: {}
mca: {}
pcamix: {}
umap:
  # For reproducibility, random_state is set. UMAP will force n_jobs to 1 in
  # this case, preventing a warning from the library.
  random_state: 42
  n_jobs: 1
  metric: euclidean
tsne: {}
phate: {}
